services:
  db:
    image: postgres:16-alpine
    container_name: attendance-app-db
    restart: always
    environment:
      POSTGRES_DB: attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: attendance-app-server
    restart: always
    build:
      context: ./apps/api-server
      args:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/attendance
    env_file:
      - ./apps/api-server/.env
    depends_on:
      - db
    ports:
      - "3000:3000"

  client:
    container_name: attendance-app-client
    restart: always
    build:
      context: ./apps/web-app
    depends_on:
      - server
    ports:
      - "3173:80"

volumes:
  pgdata:
